import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { jobQuery, jobsListQuery } from "../graphql/queries";
import { client } from "../graphql/apollo";

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  try {
    const { data } = await client.query({
      query: jobsListQuery,
    });

    return {
      props: {
        data,
      },
    };
  } catch (err) {
    console.log(err);
    return {
      props: {
        data: [],
        msg: "Error Occured",
      },
    };
  }
}

// Pass data to the page via props

export default function Home({ data }) {
  console.log("data", data);
  const { jobs } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Clone of Graphql.jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          <a href="https://graphql.jobs/">GraphQL Jobs</a> Clone
        </h1>

        <div className={styles.cards}>
          {jobs.map((job) => {
            return (
              <a key={job.id} href="/" className={styles.cardItem}>
                <h2>{job.title} &rarr;</h2>
                <p>
                  <b>{job.company.name}</b>
                </p>
                {job.cities.map((city) => {
                  return (
                    <p key={city.id}>
                      {city.name} , {city.country.name}.
                    </p>
                  );
                })}
                <p>
                  <i>{job.tags.map((tag) => tag.name).join(", ")}.</i>
                </p>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
